
server:
  port: 8181
spring:
  application:
    name: domain-processor
  cloud:
    stream:
      function:
        definition: processDomain
      bindings:
        processDomain-in-0:
          destination: web-domains
        processDomain-out-0:
          destination: active.web-domains
      kafka:
        bindings:
          processDomain-in-0:
            consumer:
              configuration:
                value:
                  deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          processDomain-out-0:
            consumer:
              configuration:
                value:
                  serializer: org.springframework.kafka.support.serializer.JsonSerializer

  kafka:
    bootstrap-servers:
      - localhost:29092
      - localhost:39092
