server:
  port: 8282
spring:
  application:
    name: domain-service
  cloud:
    stream:
      function:
        definition: serviceDomain
      bindings:
        serviceDomain-in-0:
          destination: active.web-domains
      kafka:
        bindings:
          serviceDomain-in-0:
            consumer:
              configuration:
                value:
                  deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

  kafka:
    bootstrap-servers:
      - localhost:29092
      - localhost:39092